import type { NextPage, GetStaticProps } from "next";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import imageLoader from "../../imageLoader";
import styles from "../../styles/Home.module.css";
import { GetCharacterResults, Character } from "../../types";
import { motion } from "framer-motion";
import { useState, useEffect } from "react";
import useAuth from "../../hooks/useAuth";

const Home: NextPage<{ characters: Character[] }> = ({ characters }) => {
  const { logout } = useAuth();

  const handleLogout = async () => {
    await logout();
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Characters</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col justify-center items-center">
        <div className="flex flex-row items-center justify-between h-20 w-full bg-slate-500 drop-shadow-xl">
          <h1 className="ml-5 text-2xl font-bold text-white">NavBar Logo</h1>
          <div className="mr-10 font-semibold text-lg flex items-center gap-5">
            <Link href="/characters">
              <a className="text-white hover:text-xl hover:underline hover:text-orange-400">
                Home
              </a>
            </Link>
            {/* <Link href="/characters/rs-deck">
              <a className="text-white hover:text-xl hover:underline hover:text-orange-400">
                RS Deck
              </a>
            </Link> */}
            <Link href="/aboutus">
              <a className="text-white hover:text-xl hover:underline hover:text-orange-400">
                About Us
              </a>
            </Link>
            <Link href="/contactus">
              <a className="text-white hover:text-xl hover:underline hover:text-orange-400">
                Contact Us
              </a>
            </Link>
            <a
              className="text-white bg-rose-500 rounded-full drop-shadow-xl pl-5 pt-2 pb-2 pr-5 hover:text-xl hover:bg-rose-600"
              onClick={handleLogout}
            >
              Logout
            </a>
          </div>
        </div>

        <div className="flex flex-row gap-5 flex-wrap mt-5 justify-center items-center">
          {characters.map((character, i) => {
            return (
              <motion.div
                initial={{
                  opacity: 0,
                  translateX: i % 2 === 0 ? -50 : 50,
                  translateY: -50,
                }}
                animate={{
                  opacity: 1,
                  translateX: 0,
                  translateY: 0,
                }}
                transition={{ duration: 0.3, delay: i * 0.2 }}
              >
                <div
                  key={character.id.toString()} // convert to string to avoid error
                  className="flex flex-col gap-3 border-2 justify-center items-center p-2"
                >
                  <Link href={`/characters/${character.id}`}>
                    <a>
                      <h3 className="text-xl text-slate-700 font-semibold">
                        {character.name}
                      </h3>
                    </a>
                  </Link>

                  <Image
                    loader={imageLoader}
                    unoptimized
                    src={character.image}
                    alt={character.name}
                    width="200"
                    height="200"
                  />
                </div>
              </motion.div>
            );
          })}
        </div>
      </main>
    </div>
  );
};

export const getStaticProps: GetStaticProps = async (context) => {
  const res = await fetch("https://rickandmortyapi.com/api/character");
  const { results }: GetCharacterResults = await res.json();

  return {
    props: {
      characters: results,
    },
  };
};

export default Home;
