import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import { useEffect, useState } from "react";
import { useRouter } from "next/router";
import { motion } from "framer-motion";
import { BsCart2 } from "react-icons/bs";
import { GrClose } from "react-icons/gr";

const Home: NextPage = () => {
  const router = useRouter();
  const [closeToggle, setCloseToggle] = useState(false);

  const handleCloseSidebar = () => {
    if (closeToggle) setCloseToggle(false);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="m-0 w-screen h-screen">
        <div className="w-full h-full">
          <div className="w-full h-full flex">
            {/* navbar area */}
            <div className="absolute top-0 left-0 right-0 z-10 flex items-center flex-col pointer-events-none justify-between">
              <div className="w-full flex py-2 px-0 bg-black justify-center">
                <div className="w-full flex justify-center">
                  <a
                    className="underline text-white text-sm"
                    href="https://www.candlefish.com/collections/seasonal-favorites"
                    target="_blank"
                  >
                    We are ready for Spring! Shop our fresh and floral Spring
                    Collection here.
                  </a>
                </div>
              </div>
              <div className="w-full flex px-0 justify-between">
                <div className="flex flex-row justify-center">
                  <div className="flex flex-col justify-between bg-yellow-200 w-full h-full min-w-210 hide-scrollbar">
                    {/* style editing ======================================================================== */}
                    <div className="flex flex-col justify-start items-center mt-8 mr-3 mb-8">
                      <button
                        type="button"
                        className="absolute hover:bg-slate-600 hover:rounded-full"
                      >
                        <GrClose
                          style={{ color: "white" }}
                          className="text-2xl hover:bg-slate-100 hover:rounded-full"
                        />
                      </button>
                      <div className="flex flex-col justify-center ml-8 mt-8 gap-5 text-white">
                        <img
                          src="	https://candlefish-assets.s3.amazonaws.com/assets/side-nav-background.png"
                          className="w-full h-height-full"
                        />
                        <div className="flex flex-col gap-2">
                          <h1 className="text-xl font-extrabold">Shop</h1>
                          <div className="flex flex-col ml-5 text-lg font-semibold">
                            <a href="">By Collections</a>
                            <a href="">Seasonal Picks</a>
                            <a href="">Top Sellers</a>
                            <a href="">Gift Cards</a>
                          </div>
                        </div>
                        <div className="text-xl font-extrabold">
                          <a href="">Discover</a>
                        </div>
                        <div className="text-xl font-extrabold">
                          <a href="">The Library</a>
                        </div>
                        <div className="text-xl font-extrabold">
                          <a href="">The Blog</a>
                        </div>
                        <div className="flex flex-col gap-2">
                          <h1 className="text-xl font-extrabold">About</h1>
                          <div className="flex flex-col ml-5 text-lg font-semibold">
                            <a href="">Our Story</a>
                            <a href="">Contach Us</a>
                            <a href="">Location and Hours</a>
                            <a href="">Shop Wholesale</a>
                          </div>
                        </div>
                        <div className="flex flex-col gap-3">
                          <h1 className="text-xl font-extrabold">
                            Custom Candles
                          </h1>
                          <div className="flex flex-col ml-5 text-lg font-semibold">
                            <a href="">Private Lable Services</a>
                            <a href="">Wedding Candles</a>
                          </div>
                        </div>
                        <div>
                          <div className="text-xl font-extrabold">
                            <a href="">Candle Making</a>
                          </div>
                          <div className="text-xl font-extrabold">
                            <a href="">Classes</a>
                          </div>
                        </div>
                      </div>
                      <div className="flex flex-rowe mt-12 bg-black text-white px-16 py-1 text-sm font-extrabold">
                        <Link href="/login">
                          <a>
                            <button className="rounded-sm">Login</button>
                          </a>
                        </Link>
                      </div>
                    </div>
                  </div>
                  <h3 className="text-4xl mt-3 text-white">CANDLEFISH</h3>
                </div>
                <span>
                  <BsCart2
                    style={{ color: "white" }}
                    className="w-12 h-12 mr-5"
                  />
                </span>
              </div>
            </div>

            {/* main content area */}
            <div className="flex flex-row m-0 w-full h-full">
              <div className="relative flex flex-col justify-center items-center w-2/6 hover:w-3/5">
                <img
                  src="https://candlefish-assets.s3.amazonaws.com/assets/shop-home.jpg"
                  className="w-full h-full object-cover"
                />
                <div className="absolute w-full h-full bg-black bg-opacity-30 flex flex-col justify-center items-center gap-y-16">
                  <img
                    src="	https://candlefish-assets.s3.amazonaws.com/assets/panel-expanded-icon.png"
                    className="w-20 h-20"
                  />
                  <h1 className="text-white text-5xl font-bold">SHOP</h1>
                  <ul className="text-white text-4xl font-bold underline underline-offset-8 flex flex-col gap-3">
                    <li className=" hover:cursor-pointer hover:text-right">
                      By Collections
                    </li>
                    <li className=" hover:cursor-pointer">Seasonal Picks</li>
                    <li className=" hover:cursor-pointer">Top Sellers</li>
                    <li className=" hover:cursor-pointer">Gift Cards</li>
                  </ul>
                </div>
              </div>
              <div className="relative flex flex-col justify-center items-center w-2/6 hover:w-3/5">
                <img
                  src="https://candlefish-assets.s3.amazonaws.com/assets/discover-home.jpg"
                  className="w-full h-full object-cover"
                />
                <div className="absolute w-full h-full bg-black bg-opacity-30 flex flex-col justify-center items-center gap-y-16">
                  <img
                    src="	https://candlefish-assets.s3.amazonaws.com/assets/panel-expanded-icon.png"
                    className="w-20 h-20"
                  />
                  <div className="flex flex-col gap-2 justify-center items-center">
                    <h1 className="text-white text-5xl font-bold">DISCOVER</h1>
                    <p className="text-white text-lg">
                      See what fragrance you are feeling today
                    </p>
                  </div>
                  <ul className="text-white text-4xl font-bold underline underline-offset-8 flex flex-col gap-3">
                    <li className=" hover:cursor-pointer hover:text-right">
                      DISCOVER NOW
                    </li>
                  </ul>
                </div>
              </div>
              <div className="relative flex flex-col justify-center items-center w-2/6 hover:w-3/5">
                <img
                  src="https://candlefish-assets.s3.amazonaws.com/assets/library-home.jpg"
                  className="w-full h-full object-cover"
                />
                <div className="absolute w-full h-full bg-black bg-opacity-30 flex flex-col justify-center items-center gap-y-16">
                  <img
                    src="	https://candlefish-assets.s3.amazonaws.com/assets/panel-expanded-icon.png"
                    className="w-20 h-20"
                  />
                  <div className="flex flex-col gap-2 justify-center items-center">
                    <h1 className="text-white text-5xl font-bold">
                      BROWSE
                      <br />
                      LIBRARY
                    </h1>
                    <p className="text-white text-lg">
                      See what fragrance you are feeling today
                    </p>
                  </div>
                  <ul className="text-white text-4xl font-bold underline underline-offset-8 flex flex-col gap-3">
                    <li className=" hover:cursor-pointer hover:text-right">
                      LIBRARY CARD
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
