import Head from "next/head";
import HeaderSection from "../../components/homeComponents/header";

const index = () => {
  return (
    <div>
      <Head>
        <title>Characters</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col justify-center items-center m-0 p-0 w-screen">
        <HeaderSection />
      </main>
    </div>
  );
};

export default index;
