import Head from "next/head";
import HeaderSection from "../../components/homeComponents/header";
import PreviewSection from "../../components/homeComponents/previewsection";
import PromotionSection from '../../components/homeComponents/promotionsection';
import FeaturedSection from '../../components/homeComponents/featuredsection'
import ProudProjects from '../../components/homeComponents/proudprojects'

const index = () => {
  return (
    <div>
      <Head>
        <title>Characters</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col items-center m-0 p-0 w-screen">
        <div className="w-full absolute">
          <HeaderSection />
        </div>
        <div className="w-full h-screen">
          <PreviewSection />
        </div>
        <div className="w-full h-screen">
          <PromotionSection />
        </div>
        <div className="h-screen">
          <FeaturedSection />
        </div>
        <div className="w-full h-screen">
          <ProudProjects />
        </div>
      </main>
    </div>
  );
};

export default index;
